### ISSUE TITLE
单机版sqlite ，登录界面的用户名密码是什么呀？

### ISSUE THREAD

**Issue by luckfu** [FederatedAI/FATE-Board#105]
单机版sqlite ，登录界面的用户名密码是什么呀？

**Comment by caigaga** [comment]
![image](https://user-images.githubusercontent.com/87302879/146150457-2d62f3a9-d773-4c9d-ba5d-86969637ad6c.png)
可以看下这两个配置项，一般用户名密码都默认为admin
