### ISSUE TITLE
Inappropriate  getting the fate path in `JobManagerService.java`

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE-Board#116]
Hi, I'd like to report a bug. 

In https://github.com/FederatedAI/FATE-Board/blob/0c4f24c860f2e814e563faffd10a15183d0eaede/src/main/java/com/webank/ai/fate/board/services/JobManagerService.java#L259-L262

This only works fine in the standalone deployment. (That is, the parent directory of the fate-flow and the fate-board is the same),
In the following situation, it will trigger a `File doesn't exist!` exception when the user wants to download the dsl/runtime conf in the job details dashboard. Please see the pic follows.
1. In the kube-fate docker-compose deployment: the fate-flow and fate-board are not in the same container.
2. In the standalone deployment:  If the user runs the spring-boot application in another directory(not the `/standalone_fate_install_1.7.0_release/fateboard` directory ) 

![image](https://user-images.githubusercontent.com/18736196/157599623-478b9100-95e2-4847-a039-8db14ab3bf50.png)

**Since the dsl and the runtime conf have already been stored in the table t_job, I'd like to suggest getting them from the database. If this makes scene, May I submit a PR?**

**Comment by jat001** [comment]
board 1.8 更改了读取 dsl 的方式，由直接读文件改成了使用 flow 的 api，所以没有这个问题了
