### ISSUE TITLE
使用Docker Compose部署的1.8.0集群版， fateboard使用配置文件中账密登录失败

### ISSUE THREAD

**Issue by yyouyou** [FederatedAI/FATE-Board#134]
使用Docker Compose部署的1.8.0集群版 fateboard使用配置文件中账密登录失败

#### log 
![c42f08b6488031e686f111b5a9ecefc](https://user-images.githubusercontent.com/38455904/168719222-57d67f58-84c9-497d-b598-024825479e46.png)

#### docker-deploy/parties.conf
![1652757327(1)](https://user-images.githubusercontent.com/38455904/168721175-cee700b4-3bb8-4b30-81d2-f752d091a5c9.png)

#### docker fateboard容器中application.properties
![a414e1ec02b49c12af6f6ecca151c78](https://user-images.githubusercontent.com/38455904/168720775-de467221-39b7-44c9-8937-2d91b8e4147a.png)

**Comment by jat001** [comment]
https://github.com/FederatedAI/FATE/issues/3962

**Comment by idwenwen** [comment]
可以先简单看一下是否存在这几种情况：
1. 部署好之后，使用前，浏览器缓存没有清除。
2. 浏览器的时间是否与服务器不同步，导致时间方面判别错误。

**Comment by yyouyou** [comment]
> [FederatedAI/FATE#3962](https://github.com/FederatedAI/FATE/issues/3962)

是一样的问题，容器内与外部时间不一致，已经解决

**Comment by yyouyou** [comment]
> 可以先简单看一下是否存在这几种情况：
> 
> 1. 部署好之后，使用前，浏览器缓存没有清除。
> 2. 浏览器的时间是否与服务器不同步，导致时间方面判别错误。

是问题2，容器时间与浏览器不同步
