### ISSUE TITLE
problem of my fate board web project

### ISSUE THREAD

**Issue by lylove15107** [FederatedAI/FATE-Board#22]
i just download fateboard from github.but my echart can't work. Is the newest version in master branch?

**Comment by happycooperxu** [comment]
> i just download fateboard from github.but my echart can't work. Is the newest version in master branch?

Fateboard is a component part of FATE. The echart is the display of data in FATE. Do you deploy FATE at first?

**Comment by happycooperxu** [comment]
> i just download fateboard from github.but my echart can't work. Is the newest version in master branch?

Yes. But fateboard couldn't work lonely, it's part of FATE. Please refer to https://github.com/FederatedAI/FATE/tree/master/standalone-deploy to get whole function.
