### ISSUE TITLE
add copy plugins to pom for a bit better deploy experience

### ISSUE THREAD

**Issue by weiwee** [FederatedAI/FATE-Board#28]
fateboard could be deploy with following directory structure:
```
fateboard/
  fateboard.jar
  conf/
    application.properties
    ssh.properties
```
It maybe a good idea to generate this structure in maven package phase by simply add this configuration to pom.xml:

```xml
<plugins>
...
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.10</version>
        <executions>
            <execution>
                <id>copy-dependencies</id>
                <phase>package</phase>
                <goals>
                    <goal>copy-dependencies</goal>
                </goals>
                <configuration>
                    <outputDirectory>${project.build.directory}/lib</outputDirectory>
                </configuration>
            </execution>
            <!-- code added start -->
            <execution>
                <id>copy-packaged</id>
                <phase>package</phase>
                <goals>
                    <goal>copy</goal>
                </goals>
                <configuration>
                    <artifactItems>
                        <artifactItem>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                            <version>${project.version}</version>
                            <type>${project.packaging}</type>
                            <destFileName>fateboard.jar</destFileName>
                        </artifactItem>
                    </artifactItems>
                    <outputDirectory>${project.build.directory}/fateboard</outputDirectory>
                </configuration>
            </execution>
        </executions>
    </plugin>
    <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
            <execution>
                <id>copy-resources</id>
                <!-- here the phase you need -->
                <phase>package</phase>
                <goals>
                    <goal>copy-resources</goal>
                </goals>
                <configuration>
                    <outputDirectory>${basedir}/target/fateboard/conf</outputDirectory>
                    <resources>
                        <resource>
                            <directory>src/main/resources</directory>
                            <includes>
                                <include>application.properties</include>
                                <include>ssh.properties</include>
                            </includes>
                        </resource>
                    </resources>
                </configuration>
            </execution>
        </executions>
    </plugin>
    <!-- code added end -->
</plugins>
```

We get feteboard dir after package phase:

![image](https://user-images.githubusercontent.com/18696809/71723854-26770700-2e69-11ea-8c42-e9139969ae35.png)

**Comment by happycooperxu** [comment]
> fateboard could be deploy with following directory structure:
> 
> ```
> fateboard/
>   fateboard.jar
>   conf/
>     application.properties
>     ssh.properties
> ```
> 
> It maybe a good idea to generate this structure in maven package phase by simply add this configuration to pom.xml:
> 
> ```
> <plugins>
> ...
>     <plugin>
>         <groupId>org.apache.maven.plugins</groupId>
>         <artifactId>maven-dependency-plugin</artifactId>
>         <version>2.10</version>
>         <executions>
>             <execution>
>                 <id>copy-dependencies</id>
>                 <phase>package</phase>
>                 <goals>
>                     <goal>copy-dependencies</goal>
>                 </goals>
>                 <configuration>
>                     <outputDirectory>${project.build.directory}/lib</outputDirectory>
>                 </configuration>
>             </execution>
>             
>             <execution>
>                 <id>copy-packaged</id>
>                 <phase>package</phase>
>                 <goals>
>                     <goal>copy</goal>
>                 </goals>
>                 <configuration>
>                     <artifactItems>
>                         <artifactItem>
>                             <groupId>${project.groupId}</groupId>
>                             <artifactId>${project.artifactId}</artifactId>
>                             <version>${project.version}</version>
>                             <type>${project.packaging}</type>
>                             <destFileName>fateboard.jar</destFileName>
>                         </artifactItem>
>                     </artifactItems>
>                     <outputDirectory>${project.build.directory}/fateboard</outputDirectory>
>                 </configuration>
>             </execution>
>         </executions>
>     </plugin>
>     <plugin>
>         <artifactId>maven-resources-plugin</artifactId>
>         <version>3.1.0</version>
>         <executions>
>             <execution>
>                 <id>copy-resources</id>
>                 
>                 <phase>package</phase>
>                 <goals>
>                     <goal>copy-resources</goal>
>                 </goals>
>                 <configuration>
>                     <outputDirectory>${basedir}/target/fateboard/conf</outputDirectory>
>                     <resources>
>                         <resource>
>                             <directory>src/main/resources</directory>
>                             <includes>
>                                 <include>application.properties</include>
>                                 <include>ssh.properties</include>
>                             </includes>
>                         </resource>
>                     </resources>
>                 </configuration>
>             </execution>
>         </executions>
>     </plugin>
>     
> </plugins>
> ```
> 
> We get feteboard dir after package phase:
> 
> ![image](https://user-images.githubusercontent.com/18696809/71723854-26770700-2e69-11ea-8c42-e9139969ae35.png)
An excellent idea, thanks!  But now the structure-change could effect its deploy in FATE.
