### ISSUE TITLE
[Feature Request] Enable Customized Prefix for URLs

### ISSUE THREAD

**Issue by jiahaoc1993** [FederatedAI/FATE-Board#58]
Hi, Is it possible to add a customized prefix to the Server-side?
In our scenario, we route requests base on the URL rather than the hostname, assumes we have a gateway and two fateboard services as follows:
```
          ---->  fateboard1
gateway -|
          ---->  fateboard2

```

we use the following URLs to access fatebord1 and fateboard2 respectively：
- http://gateway.domain/fateboard1
- http://gateway.domain/fateboard2

Before forwarding the request, the gateway needs to rewrite the URL from `/fateboard1` to `/`, and then send the request to `fateboard1`. However, the further requests triggered by the JS will be sent to an address without `fatebord*` pattern, for example, "http://gateway.domain/ssh". Resulting in the gateway can't forward this request correctly.

The ideal solution is to add a variable to the routing policy like `${prefix}/`, if the prefix is empty, then the use `/`.
If the prefix is `fateboard1`, then use `/fateboard1/` as the root. So that the rewrite could be avoided and further request can contain the `fatebord*` part.

**Comment by happycooperxu** [comment]
Thanks for your advise, we will consider it in the next version.
