### ISSUE TITLE
fateboard 1.5 error

### ISSUE THREAD

**Issue by cometta** [FederatedAI/FATE-Board#66]
when i start fateboard on standalone mode i get below error
![image](https://user-images.githubusercontent.com/187495/97935380-5fe31080-1db3-11eb-8460-fe60c623414e.png)

**Comment by happycooperxu** [comment]
which verison you are using? it maybe caused by the wrong properties for database or fate_flow server.

**Comment by cometta** [comment]
@happycooperxu  i'm using fateboard 1.5.  i run on standalone, i checked /fate/fateboard/conf/
application.properties , it is using sqlite, i dont see any error in Spring boot start up

fateboard.datasource.jdbc-url=jdbc:sqlite:/fate/python/fate_flow/fate_flow_sqlite.db
fateboard.datasource.username=
fateboard.datasource.password=

**Comment by cometta** [comment]
apologies, my mistake, for 1.5, there is changes for docker-compose-build.yml mount volume /fate/python/fate_flow which previously mount to /fate/fate_flow . issue resolved. Thank you
