### ISSUE TITLE
[bug] Document error

### ISSUE THREAD

**Issue by owlet42** [FederatedAI/FATE-Board#71]
https://github.com/FederatedAI/FATE-Board#frequently-asked-questions
![image](https://user-images.githubusercontent.com/21351918/98217116-fca8d800-1f84-11eb-9f27-fe0781d1a947.png)

 “The default log lookup path is /data/projects/fate/python/logs/.”
The new version of path is /data/projects/fate/logs/

**Comment by happycooperxu** [comment]
yes, you are right! We will fix it in the next version. 
Thank you!
