### ISSUE TITLE
[bug]: Part of the page cannot be opened when use HTTPS

### ISSUE THREAD

**Issue by owlet42** [FederatedAI/FATE-Board#90]
Deploy FATE-Board on K8s, use ingress-nginx for TLS certificate termination.

When I open fateboard's URL, I got some error information.

ERROR: `'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.`

![image](https://user-images.githubusercontent.com/21351918/122362903-184c7600-cf8b-11eb-87fd-be77cd5c9f11.png)

**Comment by idwenwen** [comment]
This error is due to that 'websocket' is not security. From version of 1.6.1, FATE-Board now is supporting HTTPS protocol
