### ISSUE TITLE
[BUG]Fateboard display predict_score wrong if data are in format of scientific notation.

### ISSUE THREAD

**Issue by SennriSyunnga** [FederatedAI/FATE-Board#94]
I notice a small problem in the fateboard of FATE 1.5.2.version
When you click into the data output of homo nn component in the board,
you can see some predict-scores  are more than 1.0,
For example:
If a predict scores is '8.940696716308..e-8', you will get '8.940696' only .
Here is the picture:
![QQ图片20210826141219](https://user-images.githubusercontent.com/39991122/130910433-6e933189-8912-4d35-a690-0580e57d700d.png)
Look like that it just cuts off the string according to the length.
I am not sure this problem still exists in the 1.6.x, 
can someone have a check?

**Comment by idwenwen** [comment]
Thanks for finding out this detail, we had checked this bug repeatedly and fixed it. 
The update has been released in version of 1.6.1
